[tool.black]
line-length = 100
target-version = ['py39']
skip-string-normalization = true  # Preserve single quotes

[tool.isort]
profile = "black"
line_length = 100

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"