name: PyPI Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        pytest tests/

    - name: Run linting checks
      continue-on-error: true
      run: |
        echo "Running linting checks (warnings only)..."
        flake8 chat/ tests/ chat_provider.py || echo "::warning::Linting issues found, but continuing pipeline"

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.__TOKEN__ }}
        TWINE_REPOSITORY_URL: ${{ vars.PYPI_REPOSITORY_URL }}
      run: |
        twine upload --repository-url $TWINE_REPOSITORY_URL dist/*